= Referenzimplementierung des IsyFact-Bausteins 'Security'

== Überblick

In dieser Referenzimplementierung wird die Verwendung des IsyFact-Bausteins 'Security' und seiner Komponenten (Authentifizierungsmanager und Berechtigungsmanager), sowie der Annotationen (@Secured und @Authenticate) anhand ausführbarer Java-Tests demonstriert.

Die Referenz-Implementierung beinhaltet zwei Spring-Boot-Anwendungen (ref-impl-isy-security-rw und ref-impl-isy-security-w),
deren Endpoints jeweils unter localhost:8081 und localhost:8082 über Test-Klassen aufrufbar sind.
Wesentliche Voraussetzung für das Funktionieren dieser Anwendungen und der zugehörigen Tests ist eine unter localhost:8989 gestartete KeyCloak-Installation.
Die Konfiguration von Keycloak und die erforderlichen Schritte zum Import und Export einer solchen Konfiguration sind im Dokument 'Konfiguration-KeyCloak.adoc' beschrieben.

== Fachlichkeit

Die Fachlichkeit 'Shop' des Architektur-Durchstichs (Produkte) aus 'ref-impl-basis' ist durch die
REST API der ProduktController-Klasse definiert und beinhaltet lediglich zwei GET-Methoden.
Für die Referenz-Implementierung Security wurden diese GET-Methoden beibehalten
und eine PUT-Methode zur Aktualisierung von Produkten wurde ergänzt.
Anders als die beiden GET-Methoden, die für alle Anwender uneingeschränkt aufrufbar sind,
ist die neu hinzugefügte PUT-Methode nur für bestimmte Anwender aufrufbar.

== Architektur

Wie bereits im Überblick erwähnt, wurde die oben skizzierte Fachlichkeit
auf zwei Module "RW" ('ref-impl-security-rw') und "W" ('ref-impl-security-w') aufgeteilt.

Dabei sind "RW" und "W" eigenständige Spring-Boot-Anwendungen,
wobei "W" zur Aktualisierung von Produkten die REST-Schnittstelle von "RW" verwendet.

Die Aufteilung wurde durchgeführt,
um den Anwendungsfall "Authentifizierung für externe Service-Aufrufe" zu demonstrieren.

== Berechtigungskonzept
Um Produkte über die Anwendung RW zu ändern, muss der Anwender das Recht "PRIV_Recht_A" besitzen.
Um Produkte über die Anwendung W zu ändern, muss der Anwender das Recht "PRIV_Recht_B" haben.
Vor Ausführung des externen Service-Aufrufs, authentifiziert sich die Anwendung W als ein Client, der
die Rolle A hat. Die Rolle A und das ihr zugehörige Recht "PRIV_Recht_A" werden dann an der
der Systemgrenze der aufgerufenen Anwendung RW überprüft.

== Implementierungs-Details

=== Konfigurationsklassen
Über die Klasse OAuth2ServerSecurityConfig wird definiert,
welche Resource-Endpoints (abweichend vom Default) ohne JWT zugreifbar sind.
In der Referenzimplementierung sind die GET-Methoden für Produkte des Shops der Anwendung "RW" ohne Access-Token zugänglich.

Über die Klasse WebClientSecurityConfig wird sichergestellt,
dass für sämtliche Requests, die zum Aufruf externer Services ausgeführt werden,
ein entsprechendes Access-Token aus dem Security-Kontext extrahiert und an die aufgerufene Anwendung weitergeleitet wird.
Die Anwendung "W" verwendet diesen Mechanismus, um das Access-Token and die Anwendung "RW" weiterzugeben.

=== Konfigurationseinstellungen
Alle anwendungsrelevanten Konfigurationseinstellungen sind in der application.yml Datei definiert.
Sie beinhaltet unter anderem client-ids und client-secrets, die in KeyCloak definiert sind.

=== Abhängigkeiten
Zur Absicherung von Service-Schnittstellen (Anwendung agiert als Server von geschützten Ressourcen) werden folgende Artefakte benötigt:

       <!-- IsyFact-Bausteine -->
       <dependency>
			<groupId>de.bund.bva.isyfact</groupId>
            <artifactId>isy-security</artifactId>
        </dependency>

        <!-- Spring -->
        <!-- - Security: zur Absicherung von Service-Schnittstellen: @Secured -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

Für Aufrufe von Nachbarsystemen (Anwendung agiert als Client, der auf geschützte Ressourcen zugreifen will) werden folgende Artefakte benötigt:

        <!-- IsyFact-Bausteine -->
        <!-- - Security -->
        <dependency>
            <groupId>de.bund.bva.isyfact</groupId>
            <artifactId>isy-security</artifactId>
        </dependency>

        <!-- Spring -->
        <!-- - Security: für Aufrufe von Nachbarsystemen: -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>



== Tests
Mit den implementierten Tests werden bestimmte Aspekte des Security-Bausteins geprüft.

=== Testtechnologie
Wie beim Architektur-Durchstich (Modul 'ref-impl-basis') nutzen wir zwei Arten von Tests

- Api-Tests zeigen den Aufruf von Außen. +
In diesen Tests wird mit einem WebClient gearbeitet,
um Requests zu erzeugen und an einen Server (KeyCloak oder Spring-Boot-Anwendung) zu richten.
Voraussetzung für diese Tests ist, dass alle verwendeten Server vorab gestartet wurden.

- SpringBoot-Tests zeigen den direkten Methodenaufruf von innerhalb einer IsyFact-Anwendung. +
In diesen Tests ist es nicht notwendig,
dass die Spring-Boot-Anwendung vorab gestartet wurde. Voraussetzung ist lediglich,
dass ein entsprechend konfiguriertes Keycloak verfügbar ist.
Die für die Tests erforderlichen Controller-Klassen werden über Dependency Injection bereitgestellt.
Im Gegensatz zu den Api-Tests können SpringBoot-Tests im Kontext eines Maven-Build-Prozesses
automatisiert ausgeführt werden.

=== Testgegenstände

==== Testgegenstand Security
Das Interface Security stellt die zentrale Schnittstelle bereit,
über die auf den Baustein zugegriffen wird.
Durch die Einbindung der dependency 'de.bund.bva.isyfact:isy-security' kann das Interface 'Security' direkt in die Klasse autowired und verwendet werden:

    @Autowired
    private Security security;

Die öffentlichen Methoden bieten Zugriff auf eine Liste von allen im System hinterlegten Rollen, den Berechtigungsmanager und den optionalen Authentifizierungsmanager.


==== Testgegenstand Authentifizierungsmanager
Der Authentifizierungsmanager bietet verschiedene Arten der programmatischen Authentifizierung:

- Als technischer user (Resource-Owner-Password-Credential Flow) +
-> IsyOAuth2Authentifizierungsmanager.authentifiziereSystem(...)

- Als client direkt (Client-Credential-Flow with auth-data as parameters) +
-> IsyOAuth2Authentifizierungsmanager#authentifiziereClient(...) +

Die Verwendung dieser Methoden wird im AuthenticationManagerTest demonstriert.

==== Testgegenstand Berechtigungsmanager
Der Berechtigungs-Manager bietet Methoden zum Lesen der Rollen, Rechte und Attribute des angemeldeten Anwenders und zur Prüfung, ob er ein bestimmtes Recht besitzt
oder nicht:
-> security.getBerechtigungsmanager().getRechte(...) +
-> security.getBerechtigungsmanager().hatRecht(...) +
-> security.getBerechtigungsmanager().pruefeRecht(...) +
-> security.getBerechtigungsmanager().getRollen(...) +
-> security.getBerechtigungsmanager().getTokenAttribute(...)

Die Verwendung dieser Methoden wird im BerechtigungsManagerTest demonstriert. +
Des Weiteren wird in ProduktVerwaltungImpl.findAllProduktBo - welches den use case 'Suche nach Produkten mit Produktname' umsetzt - demonstriert, wie durch Auslesen von Token-Attributen (hier: zusätzliches Anwenderattribut 'Abteilung') eine feingranulare Rechtesteuerung umgesetzt werden kann.

==== Testgegenstand @Secured
Mit der Spring-Security Annotation @Security werden die zu schützenden REST-Endpunkte annotiert.

In den Anwendungen "RW" und "W" ist dies die UPDATE-Methode der ProduktController-Klasse.

- In Anwendung "RW" wird das Recht "PRIV_Recht_A" als notwendig deklariert.
- In Anwendung "W" ist es das Recht "PRIV_Recht_B", das als notwendig deklariert ist.

Positiv-Tests und Negativ-Tests für die @Secured Annotation findet man in der Test-Klasse SecuredResourceTest

==== Testgegenstand @Authenticate
Mit der IsyFact Annotation @Authenticate kann sich ein Service einer Fachanwendung (Task / Batch)
als ein bestimmter Nutzer authentisieren. Implizit wird damit der Security-Kontext geändert.
Aus dem neuen Security-Kontext kann dann ein Token extrahiert, an einen aufzurufenden externen geschützten Service
weitergeleitet und dort geprüft werden.

- Im Modul W ist die updateProduktBo-Methode der ProduktVerwaltungImpl-Klasse mit einer solchen @Authenticate Annotation versehen:
- Der Aufruf der entsprechenden ProduktController Methode im Modul RW erfolgt in der
  Anwendungsfallklasse AwfProdukteAktualisieren.
  Der REST Request wird dort erzeugt.
  Anschließend wird dort das Ergebnis des REST Aufrufs auch wieder in Empfang genommen.
[source, java]
----
@Component
public class ProduktVerwaltungImpl implements ProduktVerwaltung {

    /**
     * updates the properties of the given product.
     * @param produktBo
     * @return updated produktBo
     */
    @Override
    @Authenticate("reg-client-a") // has "PRIV_Recht_A"
    public ProduktBo updateProduktBo(ProduktBo produktBo) throws ProduktNotFoundException {
        return awfProdukteAktualisieren.updateProduktBo(produktBo); // calls REST API of 'ref-impl-security-rw
    }
}
----

== Testklassen

Die Testklassen wurden implementiert

- weniger um die oben genannten Testgegenstände abzusichern.
  Die Absicherung der Funktionalitäten dieser Gegenstände ist bereits bei deren
  Entwicklung erfolgt.
- Sondern vielmehr um dem Entwickler deren Integration und deren Zusammenspiel
  vor Augen zu führen.
- Entsprechend stark liegt sowohl bei Spring-Boot-Tests als auch bei
  den API-Tests der Fokus auf Demonstration der Verwendung und Integration der Funktionalität der
  jeweiligen Komponente des Bausteins Security als Testgegenstand.
- Deshalb wurde auf Unit-Tests für sämtliche danach indirekt aufgerufenen
  Klassen verzichtet. Die Test-Coverage ist trotzdem hinreichend (weil
  die aufgerufenen Klassen alle tatsächlich aufgerufen und nicht gemocked werden).
  Unit-Tests des Bausteins Security und der darin enthaltenen Methoden findet sich im
  dazugehörigen Testbaustein 'isy-security-test'.

Im Folgenden geben wir einen kurzen Überblick über dIe implementierten Testklassen.
Für alle weiteren Details sollte man sich die Klassen selbst ansehen.

=== Spring Boot Tests im Modul RW
===== AuthenticationManagerTest

- testAuthenticateAsExplicitTechnUser -> authentifiziereSystem (user über confidential client als Parameter)
- testAuthenticateAsExplicitClient -> authentifiziereClient (Authentifizierungsdaten als Parameter)
- testAuthenticateAsRegisteredClient -> authentifiziere (Authentifizierungsdaten aus Konfigurationsdatei)
- testAuthenticateAsRegisteredTechnUser -> authentifiziere (Authentifizierungsdaten aus Konfigurationsdatei)

==== BerechtigungsManagerTest

- testCustomAuthorizationResourceWithoutAuthentication,
- testCustomAuthorizationResourceWithWrongAuthentication,
- testCustomAuthorizationResourceWithCorrectAuthentication -> getTokenAttribute (zusätzliches Anwenderattribut 'Abteilung')

==== PublicResourceTest
- testPublicResourceWithoutAuthentication,
- testPublicResourceWithAuthentication ->  öffentliche GET-Endpunkte erreichbar ohne und mit Access-Token

===== SecuredResourceTest
- testAccessingSecuredResourceWithoutAuthentication,
- testAccessingSecuredResourceWithWrongAuthentication,
- testAccessingSecuredResourceWithCorrectAuthentication -> gesicherter PUT-Endpunkt nur mit korrekter Autorisierung erreichbar.

=== API Tests im Modul RW
==== ProduktControllerApiTest
- testGetProduktBoByIdRequest
- testGetAllProduktBoRequest
- testPutProduktBoRequest

=== API Tests im Modul W
==== ProduktControllerApiTest
- testPutProduktBoRequest